# Generated by Django 4.1.13 on 2024-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=50)),
                ('toppings', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
