# Generated by Django 4.1.13 on 2024-03-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='size',
            field=models.CharField(default='Large', max_length=50),
        ),
    ]
