# Generated by Django 4.1.13 on 2024-03-14 22:43

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_topping_remove_menu_toppings_menu_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='size',
            field=models.CharField(default='Large', max_length=25, verbose_name=home.models.Size),
        ),
    ]
