# Generated by Django 4.1.13 on 2024-03-21 16:26

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_menu_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='size',
            field=models.CharField(max_length=25, verbose_name=home.models.Size),
        ),
    ]
