# Generated by Django 4.1.13 on 2024-03-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_menu_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='home.size'),
        ),
    ]
