# Generated by Django 4.1.13 on 2024-03-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_menu_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='size',
        ),
    ]
